### ISSUE TITLE
Completed module 2 assignments

### ISSUE THREAD

**Issue by stacianordin** [ds4owd-001/md-02-assignments-StaciaNordin#1]
@larnsce @mianzg @sskorik01 
I didn't understand when the question:   "What are the data types of the three variables used for aesthetic mappings?"  it was asked in another assignment as well.

**Comment by sskorik01** [comment]
In the code snippet you have 

(x = continent, y = lifeExp, fill = continent)

so your 3 variables are continent, lifeExp and continent again. Their data types are likely as follows:

- continent: This variable is likely categorical, representing different continents. 

- lifeExp: This variable is likely numeric, representing life expectancy.

**Comment by stacianordin** [comment]
Oh my goodness, I don’t know what my head was complicating when I read the question. Thank you for the reply!

**Comment by sskorik01** [comment]
No worries! I will close this issue as it is resolved now :)
